# 端口
server:
    port: 9001

# sa-token配置 
sa-token: 
    # SSO-相关配置
    sso:
        # SSO-Server端 统一认证地址
        auth-url: http://127.0.0.1:9000/sso/auth
        # 使用 Http 请求校验ticket (模式三)
        is-http: true
        # SSO-Server端 ticket校验地址
        check-ticket-url: http://127.0.0.1:9000/sso/checkTicket
        # 单点注销地址
        slo-url: http://127.0.0.1:9000/sso/signout
        # 查询数据地址
        get-data-url: http://127.0.0.1:9000/sso/getData
    sign:
        # API 接口调用秘钥
        secret-key: kQwIOrYvnXmSDkwEiFngrKidMcdrgKor

        
forest: 
    # 关闭 forest 请求日志打印
    log-enabled: false
        
        
        